import { describe, expect, it } from 'vitest'
import { currentBalance, monthlyExpenses, monthlyIncome, monthlySavings, savingsRate, categoryTotals, totalExpenses, totalIncome } from './analytics'
import { formatCurrency, toChetrum } from './currency'
import { categoriesFor, filterTransactions, serializeBackup, sortedTransactions, transactionsToCsv, updatedTransaction, validateBackup, type Transaction } from './finance'
import { auditEventsToCsv, auditEventsToJson, createAuditEvent } from './audit'
import { decryptBackup, encryptBackup } from './backup'
import type { Goal } from './goals'
import { budgetRemaining, budgetUsedPercent, commitmentRatio, classificationBreakdown, dueRecurringItems, monthlyCommitments, monthlyRecurringIncome, monthlyCategorySpending, type Budget, type RecurringItem } from './planning'

const items: Transaction[] = [
  { id: '1', type: 'income', amountChetrum: toChetrum(100000), categoryId: 'salary', date: '2026-09-01', paymentMethod: 'Bank Account', note: 'September salary', isRecurring: false, createdAt: '2026-09-01T01:00:00.000Z', updatedAt: '2026-09-01T01:00:00.000Z' },
  { id: '2', type: 'income', amountChetrum: toChetrum(25000), categoryId: 'rental', date: '2026-09-02', paymentMethod: 'Bank Account', note: 'Rental income', isRecurring: false, createdAt: '2026-09-02T01:00:00.000Z', updatedAt: '2026-09-02T01:00:00.000Z' },
  { id: '3', type: 'expense', amountChetrum: toChetrum(5000), categoryId: 'food', date: '2026-09-03', paymentMethod: 'Cash', note: 'Groceries, weekly', isRecurring: false, createdAt: '2026-09-03T01:00:00.000Z', updatedAt: '2026-09-03T01:00:00.000Z' },
  { id: '4', type: 'expense', amountChetrum: toChetrum(18000), categoryId: 'housing', date: '2026-09-04', paymentMethod: 'Bank Account', note: 'EMI', isRecurring: false, createdAt: '2026-09-04T01:00:00.000Z', updatedAt: '2026-09-04T01:00:00.000Z' },
  { id: '5', type: 'expense', amountChetrum: toChetrum(3000), categoryId: 'transport', date: '2026-09-05', paymentMethod: 'Cash', note: 'Fuel', isRecurring: false, createdAt: '2026-09-05T01:00:00.000Z', updatedAt: '2026-09-05T01:00:00.000Z' },
]

describe('Money Saathi finance model', () => {
  it('converts and formats chetrum precisely', () => { expect(toChetrum('100.50')).toBe(10050); expect(formatCurrency(toChetrum(100))).toBe('Nu. 100'); expect(formatCurrency(toChetrum(100.50))).toBe('Nu. 100.50'); expect(formatCurrency(toChetrum(100000))).toBe('Nu. 1,00,000') })
  it('rejects unsafe, malformed, scientific, and over-precise amounts', () => { expect(() => toChetrum('1.001')).toThrow(); expect(() => toChetrum('1e3')).toThrow(); expect(() => toChetrum('1.')).toThrow(); expect(() => toChetrum(Number.MAX_SAFE_INTEGER)).toThrow() })
  it('reconciles acceptance totals and edited expense', () => { expect(totalIncome(items)).toBe(12500000); expect(totalExpenses(items)).toBe(2600000); expect(monthlySavings(items, '2026-09')).toBe(9900000); expect(currentBalance(toChetrum(50000), items)).toBe(toChetrum(149000)); const edited = updatedTransaction(items[2], { ...items[2], amountChetrum: toChetrum(6500) }); const next = items.map(item => item.id === edited.id ? edited : item); expect(monthlyExpenses(next, '2026-09')).toBe(2750000); expect(monthlySavings(next, '2026-09')).toBe(9750000); expect(currentBalance(toChetrum(50000), next)).toBe(toChetrum(147500)) })
  it('keeps identity and createdAt while updating income and expense', () => { const income = updatedTransaction(items[0], { ...items[0], amountChetrum: 10100, type: 'income' }); const expense = updatedTransaction(items[2], { ...items[2], amountChetrum: 650000 }); expect(income.id).toBe(items[0].id); expect(income.createdAt).toBe(items[0].createdAt); expect(income.updatedAt).not.toBe(items[0].updatedAt); expect(expense.amountChetrum).toBe(650000) })
  it('sorts by transaction date then createdAt', () => { const sameDate = [{ ...items[0], id: 'old', date: '2026-09-10', createdAt: '2026-09-10T01:00:00Z' }, { ...items[1], id: 'new', date: '2026-09-10', createdAt: '2026-09-10T02:00:00Z' }]; expect(sortedTransactions(sameDate).map(item => item.id)).toEqual(['new', 'old']) })
  it('searches and filters without mutating source', () => { const result = filterTransactions(items, { query: 'groceries', type: 'expense', paymentMethod: 'Cash' }); expect(result.map(item => item.id)).toEqual(['3']); expect(items).toHaveLength(5); expect(categoriesFor('income')[0].id).toBe('salary') })
  it('escapes CSV and converts Ngultrum decimals', () => { const csv = transactionsToCsv([{ ...items[2], note: 'Tea, "milk"\nshop' }]); expect(csv).toContain('"Tea, ""milk""\nshop"'); expect(csv).toContain('5000.00') })
  it('serializes and validates complete backups', () => { const parsed = JSON.parse(serializeBackup({ transactions: items, settings: [{ key: 'app', currency: 'BTN', openingBalanceChetrum: 0, sampleData: false }], categories: [], budgets: [], recurring: [] })); expect(parsed.schemaVersion).toBe(1); expect(validateBackup(parsed).transactions).toHaveLength(5) })
  it('exports and restores goals, defaults legacy backups, and rejects invalid goal records', () => { const goal: Goal = { id: 'g1', name: 'Emergency', targetChetrum: 100000, savedChetrum: 50000, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }; const backup = JSON.parse(serializeBackup({ transactions: [], settings: [{ key: 'app', currency: 'BTN', openingBalanceChetrum: 0, sampleData: false }], categories: [], budgets: [], recurring: [], goals: [goal] })); expect(validateBackup(backup).goals).toEqual([goal]); const legacy = { ...backup }; delete legacy.goals; expect(validateBackup(legacy).goals).toEqual([]); expect(() => validateBackup({ ...backup, goals: [{ ...goal, updatedAt: 'bad' }] })).toThrow('goals') })
  it('rejects malformed and unsupported backups before restore', () => { expect(() => validateBackup({})).toThrow(); expect(() => validateBackup({ schemaVersion: 99, transactions: [], settings: [], categories: [], budgets: [], recurring: [] })).toThrow('Unsupported'); expect(() => validateBackup({ schemaVersion: 1, transactions: [{ ...items[0], amountChetrum: -1 }], settings: [], categories: [], budgets: [], recurring: [] })).toThrow() })
  it('returns null for zero-income savings rate', () => { expect(savingsRate([], '2026-09')).toBeNull(); expect(monthlyIncome(items, '2026-09')).toBe(12500000); expect(categoryTotals(items).food).toBe(500000) })
  it('rejects malformed grouping and accepts Bhutan grouping', () => { expect(toChetrum('1,000')).toBe(100000); expect(toChetrum('1,00,000')).toBe(10000000); for (const value of ['1,2,3', '10,00,00', '12,,000']) expect(() => toChetrum(value)).toThrow() })
  it('creates ordered, source-aware, allowlisted audit events', () => { const event = createAuditEvent({ eventType: 'transaction', action: 'create', resourceType: 'transaction', summary: 'Transaction created', metadata: { type: 'expense', amountChetrum: 100, password: 'hidden', note: 'private' } }, new Date('2026-09-16T00:00:00.000Z'), false); expect(event.source).toBe('offline'); expect(event.occurredAt).toBe('2026-09-16T00:00:00.000Z'); expect(event.metadata).toEqual({ type: 'expense', amountChetrum: 100 }) })
  it('escapes audit CSV and exports JSON without secrets', () => { const event = createAuditEvent({ eventType: 'backup', action: 'export', resourceType: 'backup', summary: 'Backup, created', metadata: { format: 'json' } }); expect(auditEventsToCsv([event])).toContain('"Backup, created"'); expect(auditEventsToJson([event])).not.toContain('password') })
  it('calculates budgets, classifications, commitments, and due recurring items', () => { const budget: Budget = { id: '2026-09:food', month: '2026-09', categoryId: 'food', limitChetrum: 1000000, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }; expect(monthlyCategorySpending(items, '2026-09').food).toBe(500000); expect(budgetRemaining(budget, 650000)).toBe(350000); expect(budgetUsedPercent(budget, 650000)).toBe(65); expect(classificationBreakdown(items, '2026-09')).toEqual({ essential: 1800000, flexible: 800000 }); const recurring: RecurringItem[] = [{ id: 'salary', name: 'Salary', type: 'income', amountChetrum: 10000000, categoryId: 'salary', paymentMethod: 'Bank Account', frequency: 'monthly', dayOfMonth: 30, classification: 'flexible', isCommitment: false, active: true, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }, { id: 'emi', name: 'EMI', type: 'expense', amountChetrum: 1800000, categoryId: 'housing', paymentMethod: 'Bank Account', frequency: 'monthly', dayOfMonth: 10, classification: 'essential', isCommitment: true, active: true, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }]; const rental: RecurringItem = { ...recurring[0], id: 'rental', name: 'Rental', amountChetrum: 2500000, categoryId: 'rental', dayOfMonth: 5 }; const withRental = [...recurring, rental]; expect(monthlyRecurringIncome(withRental)).toBe(12500000); expect(monthlyCommitments(withRental)).toBe(1800000); expect(commitmentRatio(withRental)).toBeCloseTo(14.4, 6); expect(monthlyRecurringIncome(recurring)).toBe(10000000); expect(monthlyCommitments(recurring)).toBe(1800000); expect(commitmentRatio(recurring)).toBe(18); expect(commitmentRatio([{ ...recurring[0], amountChetrum: 0 }])).toBeNull(); expect(dueRecurringItems(recurring, '2026-09', 10).map(item => item.id)).toEqual(['emi']) })
  it('rejects malformed planning backup records while accepting empty legacy arrays', () => { const base = JSON.parse(serializeBackup({ transactions: [], settings: [{ key: 'app', currency: 'BTN', openingBalanceChetrum: 0, sampleData: false }], categories: [], budgets: [], recurring: [] })); expect(validateBackup(base).budgets).toEqual([]); const valid = { ...base, budgets: [{ id: '2026-09:food', month: '2026-09', categoryId: 'food', limitChetrum: 1000000, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }], recurring: [{ id: 'salary', name: 'Salary', type: 'income', amountChetrum: 10000000, categoryId: 'salary', paymentMethod: 'Bank Account', frequency: 'monthly', dayOfMonth: 30, classification: 'flexible', isCommitment: false, active: true, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }] }; expect(validateBackup(valid).recurring).toHaveLength(1); expect(() => validateBackup({ ...base, budgets: [{ id: 'bad' }] })).toThrow('budgets'); expect(() => validateBackup({ ...valid, budgets: [...valid.budgets, { ...valid.budgets[0], id: 'other' }] })).toThrow('budgets'); expect(() => validateBackup({ ...valid, recurring: [valid.recurring[0], valid.recurring[0]] })).toThrow('recurring'); expect(() => validateBackup({ ...base, recurring: [{ id: 'bad' }] })).toThrow('recurring') })
  it('handles local due dates, month ends, paused items, future items, and confirmation state', () => { const base: RecurringItem = { id: 'item', name: 'Item', type: 'expense', amountChetrum: 100, categoryId: 'food', paymentMethod: 'Cash', frequency: 'monthly', dayOfMonth: 31, classification: 'flexible', isCommitment: false, active: true, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }; expect(dueRecurringItems([base], '2026-09', new Date(2026, 8, 30))).toHaveLength(1); expect(dueRecurringItems([{ ...base, dayOfMonth: 30 }], '2026-09', new Date(2026, 8, 17))).toHaveLength(0); expect(dueRecurringItems([{ ...base, dayOfMonth: 10 }], '2026-09', new Date(2026, 8, 17))).toHaveLength(1); expect(dueRecurringItems([{ ...base, active: false }, { ...base, id: 'confirmed', dayOfMonth: 1, lastConfirmedMonth: '2026-09' }], '2026-09', new Date(2026, 8, 17))).toEqual([]); expect(dueRecurringItems([base], '2026-10', new Date(2026, 8, 17))).toEqual([]) })
  it('encrypts and decrypts backups and rejects wrong passwords', async () => { const serialized = serializeBackup({ transactions: [], settings: [{ key: 'app', currency: 'BTN', openingBalanceChetrum: 0, sampleData: false }], categories: [], budgets: [], recurring: [] }); const encrypted = await encryptBackup(serialized, 'correct horse'); expect(await decryptBackup(encrypted, 'correct horse')).toHaveProperty('schemaVersion', 1); await expect(decryptBackup(encrypted, 'wrong horse')).rejects.toThrow('Could not decrypt') })
})
