import { describe, expect, it } from 'vitest'
import { addGoalProgress, adjustGoal, createGoal, goalProgressPercent, goalRemaining, goalVisualProgress, goalReached, updateGoal, validGoalDate, validateGoalRecord, type Goal } from './goals'
import { DB_STORE_NAMES, DB_VERSION } from './db'
import { currentBalance, monthlyExpenses, monthlyIncome, monthlySavings, savingsRate } from './analytics'
import { toChetrum } from './currency'

const goal: Goal = { id: 'g1', name: 'Emergency Fund', targetChetrum: 10000000, savedChetrum: 2000000, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }

describe('savings goal calculations', () => {
  it('preserves goal identity and supports editing or clearing target dates', () => { const dated = { ...goal, targetDate: '2026-12-31' }; const changed = updateGoal(dated, { name: 'Trip', targetChetrum: 20000, targetDate: '2027-01-31' }); expect(changed.targetDate).toBe('2027-01-31'); expect(changed.id).toBe(dated.id); expect(changed.createdAt).toBe(dated.createdAt); expect(changed.savedChetrum).toBe(dated.savedChetrum); const cleared = updateGoal(dated, { name: 'Trip', targetChetrum: 20000, targetDate: undefined }); expect(cleared).not.toHaveProperty('targetDate'); expect(cleared.createdAt).toBe(dated.createdAt); expect(cleared.savedChetrum).toBe(dated.savedChetrum) })
  it('creates, updates while preserving createdAt, adds progress, adjusts, and deletes through pure operations', () => { const created = createGoal({ name: ' Travel ', targetChetrum: 10000, savedChetrum: 0 }); expect(created.name).toBe('Travel'); const updated = updateGoal(created, { name: 'Trip', targetChetrum: 20000 }); expect(updated.createdAt).toBe(created.createdAt); expect(updated.savedChetrum).toBe(0); expect(addGoalProgress(updated, 5000).savedChetrum).toBe(5000); expect(adjustGoal(updated, 3000).savedChetrum).toBe(3000) })
  it('calculates 0%, 50%, 100%, and over 100%', () => { expect(goalProgressPercent({ ...goal, savedChetrum: 0 })).toBe(0); expect(goalProgressPercent({ ...goal, savedChetrum: 5000000 })).toBe(50); expect(goalProgressPercent({ ...goal, savedChetrum: 10000000 })).toBe(100); expect(goalProgressPercent({ ...goal, savedChetrum: 11000000 })).toBe(110); expect(goalVisualProgress({ ...goal, savedChetrum: 11000000 })).toBe(100); expect(goalReached({ ...goal, savedChetrum: 10000000 })).toBe(true); expect(goalRemaining({ ...goal, savedChetrum: 11000000 })).toBe(0) })
  it('requires integer chetrum values and valid calendar dates', () => { expect(validGoalDate('2026-02-28')).toBe(true); expect(validGoalDate('2026-02-31')).toBe(false); expect(validGoalDate('2026-13-01')).toBe(false); expect(validateGoalRecord(goal)).toBe(true); expect(validateGoalRecord({ ...goal, targetDate: '2026-02-31' })).toBe(false); expect(validateGoalRecord({ ...goal, createdAt: 'not-a-date' })).toBe(false); expect(validateGoalRecord({ ...goal, updatedAt: '2026-09-01' })).toBe(false); expect(validateGoalRecord({ ...goal, savedChetrum: 1.5 })).toBe(false) })
  it('does not alter finance metrics', () => { const transactions = [{ id: 't1', type: 'income' as const, amountChetrum: toChetrum(1000), categoryId: 'salary', date: '2026-09-01', paymentMethod: 'Cash' as const, note: '', isRecurring: false, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }, { id: 't2', type: 'expense' as const, amountChetrum: toChetrum(200), categoryId: 'food', date: '2026-09-02', paymentMethod: 'Cash' as const, note: '', isRecurring: false, createdAt: '2026-09-02T00:00:00.000Z', updatedAt: '2026-09-02T00:00:00.000Z' }]; const before = [currentBalance(0, transactions), monthlyIncome(transactions), monthlyExpenses(transactions), monthlySavings(transactions), savingsRate(transactions)]; addGoalProgress(goal, 100); adjustGoal(goal, 500); expect([currentBalance(0, transactions), monthlyIncome(transactions), monthlyExpenses(transactions), monthlySavings(transactions), savingsRate(transactions)]).toEqual(before) })
  it('keeps the database migration contract', () => { expect(DB_VERSION).toBe(4); expect(DB_STORE_NAMES).toContain('goals'); expect(DB_STORE_NAMES).toContain('transactions') })
})
