import type { Budget, RecurringItem } from './planning'
import { categoryLabel } from './finance'
export type ReminderSettings = { key: 'reminders'; enabled: boolean; budgetAlerts: boolean; budgetThresholdPercent: number; recurringDaysAhead: 0 | 1 | 3 | 7; browserNotifications: boolean }
export type Reminder = { id: string; kind: 'budget' | 'recurring'; title: string; body: string; severity: 'info' | 'warning'; action: 'Budget' | 'Transactions'; dueDate?: string; daysUntil?: number }
export const defaultReminderSettings: ReminderSettings = { key: 'reminders', enabled: true, budgetAlerts: true, budgetThresholdPercent: 80, recurringDaysAhead: 3, browserNotifications: false }
export function reminderKey(reminder: Reminder, month: string) { return `${month}:${reminder.kind}:${reminder.id}` }
const MONTH_LONG_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
// Deterministic long month name from a YYYY-MM (or YYYY-MM-DD) string. This is
// intentionally string-based, not Date-based: parsing "2026-09-01" through the
// Date constructor uses UTC semantics, so `toLocaleString` in a negative-offset
// timezone can roll back to the previous month (September displaying as August).
// Slicing the month field keeps the label independent of timezone, UTC offset, and DST.
export function monthLongLabel(month: string) { const index = Number(month.slice(5, 7)) - 1; return MONTH_LONG_NAMES[index] ?? month }
export function buildReminders(budgets: Budget[], recurring: RecurringItem[], spending: Record<string, number>, month: string, settingsOrToday: ReminderSettings | Date = defaultReminderSettings, maybeToday = new Date()) { const settings = settingsOrToday instanceof Date ? defaultReminderSettings : settingsOrToday; const today = settingsOrToday instanceof Date ? settingsOrToday : maybeToday; const reminders: Reminder[] = []; const lastDay = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate(); const current = new Date(today.getFullYear(), today.getMonth(), today.getDate())
  if (settings.budgetAlerts) for (const budget of budgets) { if (budget.month !== month) continue; const percent = budget.limitChetrum ? (spending[budget.categoryId] || 0) / budget.limitChetrum * 100 : 0; if (percent >= settings.budgetThresholdPercent) reminders.push({ id: budget.id, kind: 'budget', title: percent >= 100 ? 'Budget exceeded' : 'Budget nearly reached', body: `${categoryLabel(budget.categoryId)} has used ${Math.round(percent)}% of its ${monthLongLabel(month)} budget.`, severity: percent >= 100 ? 'warning' : 'info', action: 'Budget' }) }
  for (const item of recurring.filter(entry => entry.active && entry.lastConfirmedMonth !== month)) { const day = Math.min(item.dayOfMonth, lastDay); const due = new Date(today.getFullYear(), today.getMonth(), day); const days = Math.round((due.getTime() - current.getTime()) / 86400000); if (days <= settings.recurringDaysAhead) { const overdue = days < 0; const amount = `Nu. ${(item.amountChetrum / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`; const noun = item.type === 'income' ? 'was expected' : overdue ? 'is overdue by' : 'is due'; const label = days === 0 ? 'today' : days < 0 ? `${Math.abs(days)} day${Math.abs(days) === 1 ? '' : 's'}` : days === 1 ? 'tomorrow' : `in ${days} days`; reminders.push({ id: item.id, kind: 'recurring', title: overdue ? 'Recurring item overdue' : 'Recurring item due', body: `${item.name} of ${amount} ${noun} ${label}.`, severity: overdue ? 'warning' : 'info', action: 'Transactions', dueDate: due.toISOString(), daysUntil: days }) } }
  return reminders.sort((a, b) => Number(b.severity === 'warning') - Number(a.severity === 'warning')) }
