import { describe, expect, it } from 'vitest'
import { autoLockElapsed, backgroundLockDecision, createLockRecord, deriveVerifier, validPin, verifyPassword } from './security'
import { buildReminders, defaultReminderSettings } from './reminders'

describe('Phase E.1 security and reminders', () => {
  it('uses numeric PINs and never stores plaintext', async () => { const record = await createLockRecord('1234'); expect(validPin('1234')).toBe(true); expect(validPin('123')).toBe(false); expect(await verifyPassword('1234', record)).toBe(true); expect(await verifyPassword('9999', record)).toBe(false); expect(JSON.stringify(record)).not.toContain('1234'); const first = await deriveVerifier('1234', new Uint8Array(16)); const second = await deriveVerifier('1234', new Uint8Array(16).fill(1)); expect(first).not.toBe(second) })
  it('honors reminder lead settings and overdue exclusions', () => { const item = { id: 'r', name: 'EMI', type: 'expense' as const, amountChetrum: 1800000, categoryId: 'housing', paymentMethod: 'Cash' as const, frequency: 'monthly' as const, dayOfMonth: 10, classification: 'essential' as const, isCommitment: true, active: true, createdAt: '2026-09-01T00:00:00.000Z', updatedAt: '2026-09-01T00:00:00.000Z' }; const date = new Date(2026, 8, 12); expect(buildReminders([], [item], {}, '2026-09', { ...defaultReminderSettings, recurringDaysAhead: 0 }, date)).toHaveLength(1); expect(buildReminders([], [item], {}, '2026-09', { ...defaultReminderSettings, recurringDaysAhead: 0 }, date)[0].body).toContain('overdue by 2 days'); expect(buildReminders([], [{ ...item, lastConfirmedMonth: '2026-09' }], {}, '2026-09', defaultReminderSettings, date)).toHaveLength(0) })
  it('handles deterministic auto-lock timing', () => { expect(autoLockElapsed(0, 60_000, 1)).toBe(true); expect(autoLockElapsed(0, 299_999, 5)).toBe(false); expect(autoLockElapsed(0, 300_000, 5)).toBe(true); expect(autoLockElapsed(0, 900_000, 15)).toBe(true); expect(autoLockElapsed(0, 999_999, 0)).toBe(false); expect(backgroundLockDecision(0, 240_000, 5)).toBe(false); expect(backgroundLockDecision(0, 300_000, 5)).toBe(true) })
})
