'use client'

import { useState } from 'react'
import { createLockRecord, validPin, verifyPassword, type LockRecord } from '@/lib/security'

export function AppLockSettings({ record, onSave, onDisable, onLock }: { record: LockRecord | null; onSave: (record: LockRecord) => Promise<void>; onDisable: (pin: string) => Promise<boolean>; onLock: () => void }) { const [mode, setMode] = useState<'idle' | 'setup' | 'change' | 'disable'>('idle'); const [current, setCurrent] = useState(''); const [pin, setPin] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const enabled = Boolean(record?.enabled)
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (mode === 'disable') { if (await onDisable(current)) setMode('idle'); else setError('Current PIN is incorrect.'); return } if ((mode === 'change' && (!record || !(await verifyPassword(current, record)))) || !validPin(pin) || pin !== confirm) { setError('Check the current PIN and make sure the new PINs match.'); return } await onSave(await createLockRecord(pin, record?.autoLockMinutes ?? 5)); setMode('idle'); setPin(''); setConfirm(''); setCurrent('') }
  return <section className="settings-subsection"><div className="panel-heading"><div><p className="eyebrow">Privacy</p><h3>App Lock</h3></div><strong>{enabled ? 'On' : 'Off'}</strong></div>{mode === 'idle' ? <div className="settings-actions">{enabled ? <><label className="settings-inline">Auto-lock<select value={record?.autoLockMinutes ?? 5} onChange={event => void onSave({ ...record!, autoLockMinutes: Number(event.target.value) })}><option value="0">Never automatically</option><option value="1">1 minute</option><option value="5">5 minutes</option><option value="15">15 minutes</option></select></label><button className="secondary-button" onClick={() => setMode('change')}>Change PIN</button><button className="secondary-button" onClick={() => setMode('disable')}>Disable App Lock</button><button className="secondary-button" onClick={onLock}>Lock app now</button></> : <button className="primary-button" onClick={() => setMode('setup')}>Enable App Lock</button>}</div> : <form className="settings-form" onSubmit={submit}>{mode === 'change' && <label>Current PIN<input inputMode="numeric" type="password" value={current} onChange={event => setCurrent(event.target.value)}/></label>}{mode === 'disable' && <label>Current PIN<input inputMode="numeric" type="password" value={current} onChange={event => setCurrent(event.target.value)}/></label>}{mode !== 'disable' && <><label>New PIN<input inputMode="numeric" type="password" value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, '').slice(0, 8))}/></label><label>Confirm PIN<input inputMode="numeric" type="password" value={confirm} onChange={event => setConfirm(event.target.value.replace(/\D/g, '').slice(0, 8))}/></label></>}{error && <p className="form-error">{error}</p>}<button className="primary-button">{mode === 'disable' ? 'Disable App Lock' : 'Save PIN'}</button><button className="text-button" type="button" onClick={() => setMode('idle')}>Cancel</button></form>}</section>
}
