'use client'

import { useState } from 'react'
import { Plus, Pencil, SlidersHorizontal, Trash2 } from 'lucide-react'
import { toChetrum } from '@/lib/currency'
import { formatGoalDate, goalAmountLabel, goalDisplayPercent, goalReached, goalRemainingLabel, goalVisualProgress, type Goal } from '@/lib/goals'
import { useModalDialog } from '@/components/money-saathi/dialogs/use-modal-dialog'

type EditInput = { name: string; targetChetrum: number; targetDate?: string }
type Props = { goals: Goal[]; onCreate: (input: { name: string; targetChetrum: number; savedChetrum: number; targetDate?: string }) => Promise<void>; onEdit: (goal: Goal, input: EditInput) => Promise<void>; onAddProgress: (goal: Goal, amountChetrum: number) => Promise<void>; onAdjust: (goal: Goal, savedChetrum: number) => Promise<void>; onDelete: (goal: Goal) => Promise<void> }

function GoalForm({ initial, editing, onSubmit, onCancel, submitLabel }: { initial?: Partial<Goal>; editing?: boolean; onSubmit: (input: { name: string; targetChetrum: number; savedChetrum: number; targetDate?: string }) => Promise<void>; onCancel: () => void; submitLabel: string }) { const [name, setName] = useState(initial?.name || ''); const [target, setTarget] = useState(initial?.targetChetrum ? String(initial.targetChetrum / 100) : ''); const [saved, setSaved] = useState(initial?.savedChetrum ? String(initial.savedChetrum / 100) : ''); const [date, setDate] = useState(initial?.targetDate || ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); if (saving) return; const targetChetrum = toChetrum(target); const savedChetrum = editing ? initial?.savedChetrum || 0 : (saved.trim() ? toChetrum(saved) : 0); if (!name.trim()) return setError('Enter a goal name.'); if (!Number.isSafeInteger(targetChetrum) || targetChetrum <= 0) return setError('Enter a target amount greater than zero.'); if (!editing && (!Number.isSafeInteger(savedChetrum) || savedChetrum < 0)) return setError('Enter a valid saved amount.'); setSaving(true); try { await onSubmit({ name, targetChetrum, savedChetrum, targetDate: date || undefined }) } catch { setSaving(false); setError('Could not save this goal. Try again.') } } return <form className="goal-form" onSubmit={submit}><label>Goal name<input value={name} onChange={event => setName(event.target.value)} placeholder="Emergency fund" required disabled={saving}/></label><label>Target amount<input value={target} onChange={event => setTarget(event.target.value)} placeholder="Nu. 100,000" inputMode="decimal" required disabled={saving}/></label>{!editing && <label>Already saved <span className="muted">(optional)</span><input value={saved} onChange={event => setSaved(event.target.value)} placeholder="Nu. 0" inputMode="decimal" disabled={saving}/></label>}<label>Target date <span className="muted">(optional)</span><input type="date" value={date} onChange={event => setDate(event.target.value)} disabled={saving}/></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={onCancel} disabled={saving}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : submitLabel}</button></div></form> }

function ProgressForm({ goal, add, onCancel, onSubmit }: { goal: Goal; add: boolean; onCancel: () => void; onSubmit: (amount: number) => Promise<void> }) { const [value, setValue] = useState(add ? '' : String(goal.savedChetrum / 100)); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); if (saving) return; const amount = toChetrum(value); if (!Number.isSafeInteger(amount) || (add ? amount <= 0 : amount < 0)) return setError(add ? 'Enter an amount greater than zero.' : 'Enter a valid saved amount.'); setSaving(true); try { await onSubmit(amount) } catch { setSaving(false); setError('Could not save progress. Try again.') } } return <form className="goal-form" onSubmit={submit}><p className="subheading">Current saved: Nu. {(goal.savedChetrum / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</p><label>{add ? 'Amount to add' : 'Saved amount'}<input autoFocus value={value} onChange={event => setValue(event.target.value)} placeholder="Nu. 15,000" inputMode="decimal" disabled={saving} required/></label>{add && <p className="form-hint">This updates goal progress only. It does not create a transaction or change your balance.</p>}{error && <p className="form-error">{error}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={onCancel} disabled={saving}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : add ? 'Add progress' : 'Save progress'}</button></div></form> }

function GoalCard({ goal, onEdit, onAdd, onAdjust, onDelete }: { goal: Goal; onEdit: () => void; onAdd: () => void; onAdjust: () => void; onDelete: () => void }) { const percent = goalDisplayPercent(goal); return <article className="goal-card"><div className="goal-card-heading"><div><h3>{goal.name}</h3>{goalReached(goal) && <span className="goal-reached">Goal reached</span>}</div><div className="goal-card-actions"><button className="icon-button" onClick={onEdit} aria-label={`Edit ${goal.name}`}><Pencil size={16}/></button><button className="icon-button" onClick={onDelete} aria-label={`Delete ${goal.name}`}><Trash2 size={16}/></button></div></div><div className="goal-amounts"><strong>{goalAmountLabel(goal)}</strong><strong>{percent}</strong></div><div className="goal-progress" role="progressbar" aria-label={`${goal.name} progress`} aria-valuenow={Math.min(100, Number(percent.replace('%', '')))} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${goalVisualProgress(goal)}%` }}/></div><div className="goal-meta"><span>{goalRemainingLabel(goal)}</span>{goal.targetDate && <span>Target: {formatGoalDate(goal.targetDate)}</span>}</div><div className="goal-actions"><button className="secondary-button" onClick={onAdd}><Plus size={15}/> Add progress</button><button className="secondary-button" onClick={onAdjust}><SlidersHorizontal size={15}/> Adjust saved amount</button></div></article> }

export function GoalsView({ goals, onCreate, onEdit, onAddProgress, onAdjust, onDelete }: Props) { const [mode, setMode] = useState<'none' | 'create' | 'edit' | 'add' | 'adjust'>('none'); const [selected, setSelected] = useState<Goal | null>(null); const open = (goal: Goal, next: 'edit' | 'add' | 'adjust') => { setSelected(goal); setMode(next) }; const closeModal = () => setMode('none'); const editRef = useModalDialog<HTMLDivElement>({ open: mode !== 'none' && mode !== 'create' && Boolean(selected), onClose: closeModal }); const createRef = useModalDialog<HTMLDivElement>({ open: mode === 'create', onClose: closeModal }); return <section className="goals-page"><div className="panel-heading"><div><p className="eyebrow">Savings goals</p><h1>Goals</h1><p className="subheading">Save towards something that matters to you.</p></div><button className="primary-button" onClick={() => setMode('create')}><Plus size={16}/> Create goal</button></div>{goals.length === 0 ? <div className="empty-state"><h2>What are you saving for?</h2><p>A trip, emergency fund, education, home, or something else.</p><button className="primary-button" onClick={() => setMode('create')}>Create a goal</button></div> : <div className="goal-list">{goals.map(goal => <GoalCard key={goal.id} goal={goal} onEdit={() => open(goal, 'edit')} onAdd={() => open(goal, 'add')} onAdjust={() => open(goal, 'adjust')} onDelete={() => void onDelete(goal)}/>)}</div>}{mode !== 'none' && mode !== 'create' && selected && <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) closeModal() }}><div className="add-sheet" role="dialog" aria-modal="true" aria-label={mode === 'edit' ? 'Edit goal' : mode === 'add' ? 'Add progress' : 'Adjust saved amount'} ref={editRef}><h2>{mode === 'edit' ? 'Edit goal' : mode === 'add' ? 'Add progress' : 'Adjust saved amount'}</h2>{mode === 'edit' ? <GoalForm initial={selected} editing submitLabel="Save changes" onCancel={() => setMode('none')} onSubmit={async input => { await onEdit(selected, { name: input.name, targetChetrum: input.targetChetrum, targetDate: input.targetDate }); setMode('none') }}/> : <ProgressForm goal={selected} add={mode === 'add'} onCancel={() => setMode('none')} onSubmit={async amount => { if (mode === 'add') await onAddProgress(selected, amount); else await onAdjust(selected, amount); setMode('none') }}/>}</div></div>}{mode === 'create' && <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) closeModal() }}><div className="add-sheet" role="dialog" aria-modal="true" aria-label="Create goal" ref={createRef}><h2>Create goal</h2><GoalForm submitLabel="Create goal" onCancel={() => setMode('none')} onSubmit={async input => { await onCreate(input); setMode('none') }}/></div></div>}</section> }
