'use client'

import { useState } from 'react'
import { Plus, Pencil, SlidersHorizontal, Trash2 } from 'lucide-react'
import { toChetrum } from '@/lib/currency'
import { formatGoalDate, goalAmountLabel, goalDisplayPercent, goalReached, goalRemainingLabel, goalVisualProgress, type Goal } from '@/lib/goals'

type Props = { goals: Goal[]; onCreate: (input: { name: string; targetChetrum: number; savedChetrum: number; targetDate?: string }) => Promise<void>; onEdit: (goal: Goal, input: { name: string; targetChetrum: number; targetDate?: string }) => Promise<void>; onAdjust: (goal: Goal, savedChetrum: number) => Promise<void>; onDelete: (goal: Goal) => Promise<void> }

function GoalForm({ initial, onSubmit, onCancel, submitLabel }: { initial?: Partial<Goal>; onSubmit: (input: { name: string; targetChetrum: number; savedChetrum: number; targetDate?: string }) => Promise<void>; onCancel: () => void; submitLabel: string }) { const [name, setName] = useState(initial?.name || ''); const [target, setTarget] = useState(initial?.targetChetrum ? String(initial.targetChetrum / 100) : ''); const [saved, setSaved] = useState(initial?.savedChetrum ? String(initial.savedChetrum / 100) : ''); const [date, setDate] = useState(initial?.targetDate || ''); const [error, setError] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); const targetChetrum = toChetrum(target); const savedChetrum = saved.trim() ? toChetrum(saved) : 0; if (!name.trim()) return setError('Enter a goal name.'); if (!Number.isSafeInteger(targetChetrum) || targetChetrum <= 0) return setError('Enter a target amount greater than zero.'); if (!Number.isSafeInteger(savedChetrum) || savedChetrum < 0) return setError('Enter a valid saved amount.'); await onSubmit({ name, targetChetrum, savedChetrum, targetDate: date || undefined }) } return <form className="goal-form" onSubmit={submit}><label>Goal name<input value={name} onChange={event => setName(event.target.value)} placeholder="Emergency fund" required/></label><label>Target amount<input value={target} onChange={event => setTarget(event.target.value)} placeholder="Nu. 100,000" inputMode="decimal" required/></label><label>Already saved <span className="muted">(optional)</span><input value={saved} onChange={event => setSaved(event.target.value)} placeholder="Nu. 0" inputMode="decimal"/></label><label>Target date <span className="muted">(optional)</span><input type="date" value={date} onChange={event => setDate(event.target.value)}/></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={onCancel}>Cancel</button><button className="primary-button" type="submit">{submitLabel}</button></div></form> }

function GoalCard({ goal, onEdit, onAdjust, onDelete }: { goal: Goal; onEdit: () => void; onAdjust: () => void; onDelete: () => void }) { const percent = goalDisplayPercent(goal); return <article className="goal-card"><div className="goal-card-heading"><div><h3>{goal.name}</h3>{goalReached(goal) && <span className="goal-reached">Goal reached</span>}</div><div className="goal-card-actions"><button className="icon-button" onClick={onEdit} aria-label={`Edit ${goal.name}`}><Pencil size={16}/></button><button className="icon-button" onClick={onDelete} aria-label={`Delete ${goal.name}`}><Trash2 size={16}/></button></div></div><div className="goal-amounts"><strong>{goalAmountLabel(goal)}</strong><strong>{percent}</strong></div><div className="goal-progress" role="progressbar" aria-label={`${goal.name} progress`} aria-valuenow={Math.min(100, Number(percent.replace('%', '')))} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${goalVisualProgress(goal)}%` }}/></div><div className="goal-meta"><span>{goalRemainingLabel(goal)}</span>{goal.targetDate && <span>Target: {formatGoalDate(goal.targetDate)}</span>}</div><button className="secondary-button goal-adjust" onClick={onAdjust}><SlidersHorizontal size={15}/> Adjust progress</button></article> }

export function GoalsView({ goals, onCreate, onEdit, onAdjust, onDelete }: Props) { const [mode, setMode] = useState<'none' | 'create' | 'edit' | 'adjust'>('none'); const [selected, setSelected] = useState<Goal | null>(null); const [adjusted, setAdjusted] = useState(''); const openAdjust = (goal: Goal) => { setSelected(goal); setAdjusted(String(goal.savedChetrum / 100)); setMode('adjust') }; return <section className="goals-page"><div className="panel-heading"><div><p className="eyebrow">Savings goals</p><h1>Savings goals</h1><p className="subheading">Save towards something that matters to you.</p></div><button className="primary-button" onClick={() => setMode('create')}><Plus size={16}/> Create goal</button></div>{goals.length === 0 ? <div className="empty-state"><h2>No savings goals yet</h2><p>Create a goal for something you want to save towards.</p><p className="form-hint">{['Emergency fund', 'Vehicle', 'Education', 'Travel', 'Home'].join(' · ')}</p><button className="primary-button" onClick={() => setMode('create')}>Create goal</button></div> : <div className="goal-list">{goals.map(goal => <GoalCard key={goal.id} goal={goal} onEdit={() => { setSelected(goal); setMode('edit') }} onAdjust={() => openAdjust(goal)} onDelete={() => void onDelete(goal)}/>)}</div>}{mode === 'create' && <div className="modal-backdrop"><div className="add-sheet"><h2>Create goal</h2><GoalForm submitLabel="Create goal" onCancel={() => setMode('none')} onSubmit={async input => { await onCreate(input); setMode('none') }}/></div></div>}{mode === 'edit' && selected && <div className="modal-backdrop"><div className="add-sheet"><h2>Edit goal</h2><GoalForm initial={selected} submitLabel="Save changes" onCancel={() => setMode('none')} onSubmit={async input => { await onEdit(selected, input); setMode('none') }}/></div></div>}{mode === 'adjust' && selected && <div className="modal-backdrop"><div className="add-sheet"><h2>Adjust progress</h2><p className="subheading">Current saved: Nu. {(selected.savedChetrum / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</p><form className="goal-form" onSubmit={async event => { event.preventDefault(); const amount = toChetrum(adjusted); if (!Number.isSafeInteger(amount) || amount < 0) return; await onAdjust(selected, amount); setMode('none') }}><label>Set saved amount<input value={adjusted} onChange={event => setAdjusted(event.target.value)} inputMode="decimal" autoFocus/></label><div className="form-actions"><button className="secondary-button" type="button" onClick={() => setMode('none')}>Cancel</button><button className="primary-button" type="submit">Save amount</button></div></form></div></div>}</section> }
